FROM maven:3.9-eclipse-temurin-21

WORKDIR /app

COPY . .
RUN mvn dependency:purge-local-repository
RUN mvn -U clean package -DskipTests

ENTRYPOINT ["java","-jar","target/config-server-0.0.1-SNAPSHOT.jar"]